### ISSUE TITLE
Aspnet core startup

### ISSUE THREAD

**Issue by dalton5** [adams85/aspnetskeleton#1]
Hi,

What is wrong in my startup class? Did I miss something ?

I setup trnaslation like this:

services.AddSingleton<IStringLocalizerFactory, TextLocalizerFactory>();
            services.AddSingleton<IStringLocalizer, POStringLocalizer>();
            services.AddLocalization(options => options.ResourcesPath = "Resources");

            services.AddMvc().SetCompatibilityVersion(CompatibilityVersion.Version_2_1).AddControllersAsServices();

            services.Configure<RequestLocalizationOptions>(
        options =>
        {
            var supportedCultures = new List<CultureInfo>
                {
                    new CultureInfo("en-US"),
                    new CultureInfo("fr-FR"),
                };

            options.DefaultRequestCulture = new RequestCulture(culture: "en-US", uiCulture: "en-US");
            options.SupportedCultures = supportedCultures;
            options.SupportedUICultures = supportedCultures;

            options.RequestCultureProviders.Insert(0, new QueryStringRequestCultureProvider());
        });

**Comment by adams85** [comment]
Hi!

I transferred your issue as it has not much to do with PO parsing.

In regard to your question, it's hard to answer because you didn't supply too many details.

What goes wrong? Is it some compilation or run-time error? Or your app runs fine but texts don't get translated?

You may checkout this sample app I made for another lib of mine:

Setup: https://github.com/adams85/bundling/blob/master/samples/JsTranslation/Startup.cs#L30
PO localization components: https://github.com/adams85/bundling/tree/master/samples/JsTranslation/Infrastructure/Localization

It follows the standard ASP.NET Core setup which is a much simpler than the Skeleton project's one. This is pretty much all you need to get it work. (Just ignore the bundling stuff.)

I hope this will help!

**Comment by dalton5** [comment]
Hi,

It's perfect. Thanks

A ,quick question, I would like a singetion to call my trnaslation system
such as:

IStringLocalizer T = POStringLocalizer.Instance;
RuleFor(vm => vm.Email).NotEmpty().WithMessage(T["Email cannot be empty"]);

How can I do that?

Thanks,

**Comment by adams85** [comment]
IMO a static singleton doesn't seem to be a good idea. In ASP.NET Core we have DI, the `POStringLocalizer` instance should be obtained from the DI container.

As I understand it, you use some kind of fluent API to setup validation for your models. Just place this setup logic in one (or more) classes (which inject `IStringLocalizer` in their ctors), register them as singleton services in the DI container (in `Startup.ConfigureServices`). Then you can inject these setup classes in `Startup.Configure` and execute their setup logic.

**Comment by dalton5** [comment]
I found a solution.

Is it the correct way to do this?

 public static POStringLocalizer Instance;

        public POStringLocalizer(CultureInfo culture, Func<CultureInfo,
POCatalog> getCatalogForCulture, ILogger<POStringLocalizer> logger)
        {
            _catalog = getCatalogForCulture(culture);
            _getCatalogForCulture = getCatalogForCulture;
            _logger = logger;
            Instance = this;
        }

Le ven. 24 mai 2019 à 09:45, Alexis Meilland <alexis.meilland@gmail.com> a
écrit :

> Hi,
>
> It's perfect. Thanks
>
> A ,quick question, I would like a singetion to call my trnaslation system
> such as:
>
> IStringLocalizer T = POStringLocalizer.Instance;
> RuleFor(vm => vm.Email).NotEmpty().WithMessage(T["Email cannot be empty"]);
>
> How can I do that?
>
> Thanks,
>

**Comment by adams85** [comment]
Technically this may work but it's a bad practice. On the one hand, you rely on the assumption that `POStringLocalizer` is constructed only once. On the other hand, `Instance` won't be available before the `POStringLocalizer` is constructed by the IoC container the first time.

Avoid static instances, just use DI to resolve dependencies. See my previous comment.
